Aula4/Aula4/Models/ProdutoViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Aula4.Models
{
    public class ProdutoViewModel
    {
        public int id { get; set; }

        [Required(ErrorMessage = "Informe o nome do produto")]
        [StringLength(150, MinimumLength = 4)]
        public string Nome { get; set; }


        [Required(ErrorMessage = "A descrição do produto é obrigatória")]
        [StringLength(255, MinimumLength = 10)]
        public string Descricao { get; set; }
    }
}

Aula4/Aula4/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Aula4.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Esta é a nossa aplicação bacana...";
            ViewBag.MeuTextoBacana = "Que coisa legal.....";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Aula4/Aula4/Controllers/ProdutoController.cs
using Aula4.Models;
using System.Collections.Generic;
using System.Web.Mvc;

namespace Aula4.Controllers
{
    public class ProdutoController : Controller
    {
        List<ProdutoViewModel> ListaDeProdutos = new List<ProdutoViewModel>();
        private int idgeral;
        public ProdutoController()
        {
            for (int i = 1; i <= 10; i++)
            {
                ListaDeProdutos.Add(new ProdutoViewModel { id  = i, Nome = $"Produto {i}" , Descricao = $"Descrição {i}"} );
            }

            idgeral = 10;
        }

        public ActionResult Index()
        {
            return View(ListaDeProdutos);
        }



        [System.Web.Mvc.HttpGet]
        public ActionResult Criar()
        {
            return View(new ProdutoViewModel());
        }

        [System.Web.Http.HttpPost]
        public ActionResult Criar(ProdutoViewModel produto)
        {
            idgeral++;
            produto.id = idgeral;
            ListaDeProdutos.Add(produto);
            return View(produto);
        }

    }
}

Aula4/Aula4/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>
<p>@ViewBag.MeuTextoBacana</p>

Aula4/Aula4/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    Arleys castro<br />
    casa, Rua um n 0<br />
    <abbr title="Phone">P:</abbr>
    1111-00000
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Aula4/Aula4/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}


<div class="row">
    <p>Bem vindo</p>
</div>

Aula4/Aula4/Views/Produto/Criar.cshtml
@model Aula4.Models.ProdutoViewModel

@{
    ViewBag.Title = "Criar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Criar</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Cadastro de produto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Gravar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar Para a Lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Aula4/Aula4/Views/Produto/Index.cshtml
@model List<Aula4.Models.ProdutoViewModel>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="container-fluid">
    <h1> Lista de produtos</h1>
</section>

<section class="container container-fluid">
    <div class="body-content">
        @Html.ActionLink("Criar novo produto", "Criar", "Produto")
    </div>
    <div class="body-content">
        <table class="table table-responsive table-striped">
            <thead>
            <tr>
                <th>#ID</th>
                <th>NOME</th>
                <th>DESCRIÇÃO</th>
            </tr>
            </thead>
            <tbody>
            @foreach (var um in Model)
            {
                <tr>
                    <td> @Html.DisplayFor(mdi => um.id) </td>
                    <td> @Html.DisplayFor(mdi => um.Descricao) </td>
                    <td> @Html.DisplayFor(mdi => um.Nome) </td>
                </tr>
            }
            </tbody>
        </table>
    </div>
</section>

Aula4/Aula4/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Sobre", "About", "Home")</li>
                    <li>@Html.ActionLink("Contato", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Gestão do Produto", "Index", "Produto")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Minha aplicação registrada só Kaô....</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>